change auth and some styles
Obschak/frontend pull request #13
Opened 2023-09-12 13:09 UTC by nik-f-dev

2023-09-12 13:11 UTC, Arillaxe requested changes

2023-09-12 13:11 UTC, Arillaxe commented on src/pages/Auth/Auth.tsx
> +import { Navigate } from 'react-router-dom';
reorder imports

2023-09-12 13:11 UTC, Arillaxe commented on src/pages/Profile/Profile.tsx
> +  }
```suggestion
  const navigate = useNavigate();
  const dispatch = useAppDispatch();
  const { toggleTheme, theme } = useThemeContext();

  const { picture, name } = useAppSelector(({ auth }) => auth);
  const themeLogo = theme === 'light' ? moonLogo : sunLogo;

  const logOutHandle = () => {
    googleLogout();
    localStorage.removeItem(USER_TOKEN_KEY);
    dispatch(logout());
    navigate("/auth")
  };
```

2023-09-13 01:27 UTC, nik-f-dev commented on src/pages/Profile/Profile.tsx
> +  }
Такая реализация не работает без обертки в компонент, который проверяет токен. Потому что я могу нажать на кнопку назад и попасть в http://localhost:5173/#/profile, на который я попасть не должен если разлогинился.

2023-09-13 09:51 UTC, Arillaxe approved these changes

2023-09-13 09:51 UTC, Arillaxe commented on src/pages/Auth/Auth.tsx
> +import { Navigate } from 'react-router-dom';
шо ты резолвишь, импорт подвинь

2023-09-13 09:51 UTC, Arillaxe commented on src/pages/Profile/Profile.tsx
> +import { useNavigate } from 'react-router-dom';
импорт подвинь

2023-09-13 09:51 UTC, Arillaxe commented on src/pages/Profile/Profile.tsx
> +import { googleLogout } from '@react-oauth/google';
импорт

2023-09-13 09:51 UTC, Arillaxe commented on src/pages/Profile/Profile.tsx
> +import { useAppDispatch, useAppSelector } from '../../store/hooks';
все импорты организуй

2023-09-13 10:20 UTC, merged